version: "3.9"
   
services:
  db:
    build: '../database'
    env_file:
    - ./envs/.env.database
    volumes:
      - /var/lib/postgresql/data
    restart: always
  api:
    build: '.'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env.backend
    depends_on:
      - db